### ISSUE TITLE
Invoice creation fails with HTTP 400

### ISSUE THREAD

**Issue by martinfrick** [SAP-samples/btp-create-api-integrations#7]
**Issue:** When triggering the invoice creation, the service does not return a success message. In the pod logs you can see the following error message which is thrown right after the POST call is reaching the action endpoint.

[cds] - POST /invoicing/createStripeInvoices       
StripeInvalidRequestError: The search feature is temporarily unavailable in your region.
... 
statusCode: 400,        
charge: undefined,        
decline_code: undefined,        
payment_intent: undefined,
...        

**Solution:** Your Stripe account is probably setup in **India**. India is the only country not supporting a dedicated search feature required by the solution. Please create another Stripe account in any other country than India. You can do so by clicking on the name of your Stripe account in the top left when being logged in on the stripe.com website.

**Comment by jmsrpp** [comment]
Thanks a lot for this @martinfrick!
